M48
; DRILL file {KiCad 8.0.6} date 2024-11-14T02:25:44-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-14T02:25:44-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X4.7006Y-3.4295
X4.7006Y-3.6571
T2
X4.8819Y-4.5512
X4.8819Y-4.8189
M30
